name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: UTC
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v5.0.0
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af  # v6.1.0
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run plan:dry
      - run: npm run lint
      - name: Type check (Phase-1 DoD)
        run: npm run type-check
      - run: npm test
      - name: Smoke P1 (two-agent loop)
        run: npm run smoke:p1
      # Dev servers/watchers are not suitable for CI. Replace with a fast check or remove.
      # - run: npm run dev
      - run: npm run check:fast
