name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm ci
      - run: npm run plan:dry
      - run: npm run lint
      - run: npm test
      - name: Type check (Phase-1 DoD)
        run: npm run type-check
      - name: Smoke P1 (two-agent loop)
        run: npm run smoke:p1
      - run: npm run dev
