name: CodeRabbit Deep Audit
on:
  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request number to audit"
        required: true
        type: number
permissions:
  contents: read
  pull-requests: write
jobs:
  request-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'deep-audit' label
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr edit ${{ inputs.pr }} --add-label "deep-audit"
      - name: Comment to request deep audit
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr comment ${{ inputs.pr }} --body "Requesting **deep audit** by CodeRabbitAI."
