name: OpenSSF Scorecard
on:
  pull_request: { branches: [ "main" ] }
  push: { branches: [ "main" ] }
  # Staggered from CodeQL (1 AM) to avoid concurrent security scans
  schedule: [ { cron: "23 3 * * 1" } ]
permissions:
  contents: read
  id-token: write
  security-events: write
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OpenSSF Scorecard analysis
        uses: ossf/scorecard-action@v2.2.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
